apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cspo
    app.kubernetes.io/part-of: cspo
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cspo
    app.kubernetes.io/part-of: cspo
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: GIT_PROVIDER
          valueFrom:
            secretKeyRef:
              name: cspo-cluster-stack-variables
              key: git-provider
        - name: GIT_ORG_NAME
          valueFrom:
            secretKeyRef:
              name: cspo-cluster-stack-variables
              key: git-org-name
        - name: GIT_REPOSITORY_NAME
          valueFrom:
            secretKeyRef:
              name: cspo-cluster-stack-variables
              key: git-repo-name
        - name: GIT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cspo-cluster-stack-variables
              key: git-access-token
        - name: OCI_REGISTRY
          valueFrom:
            secretKeyRef:
              name: cso-cluster-stack-variables
              key: oci-registry
        - name: OCI_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: cso-cluster-stack-variables
              key: oci-repository
        - name: OCI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cso-cluster-stack-variables
              key: oci-access-token
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
