apiVersion: infrastructure.clusterstack.x-k8s.io/v1alpha1
kind: OpenStackClusterStackReleaseTemplate
metadata:
  name: cspotemplate
  namespace: cluster
spec:
  template:
    spec: {}
    # Field identityRef is optional and its default values ​​are as follows:
    # identityRef.kind: "Secret", identityRef.name: "openstack"
      # identityRef:
      #   kind: Secret
      #   name: "<your-secret-name>"
