apiVersion: v1
data:
  # The default value of `cloudName` is configured as `openstack`.
  # This can be overridden by including the `cloudName` key in this secret.
  # cloudName: "openstack"
  clouds.yaml: ${ENCODED_CLOUDS_YAML}
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  # Note: Value of the field `name` must be the same as the value of field
  # `identityRef.name` in OpenStackClusterStackReleaseTemplate object.
  name: "openstack"
  namespace: cluster
