---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - openstackclusterstackreleases
  - openstacknodeimagereleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - openstackclusterstackreleases/finalizers
  - openstacknodeimagereleases/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - openstackclusterstackreleases/status
  - openstacknodeimagereleases/status
  verbs:
  - get
  - patch
  - update
