image:
  repository: ghcr.io/sovereigncloudstack/cspo
  pullPolicy: IfNotPresent
  tag: "v0.1.0-alpha.5"
source: "oci"
oci:
  registry: "registry.scs.community"
  repository: "registry.scs.community/csctl-oci/openstack"
  access_token: ""
  username: ""
  password: ""
