//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/gophercloud/gophercloud/openstack/imageservice/v2/images"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha7"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackRelease) DeepCopyInto(out *OpenStackClusterStackRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackRelease.
func (in *OpenStackClusterStackRelease) DeepCopy() *OpenStackClusterStackRelease {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackClusterStackRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseList) DeepCopyInto(out *OpenStackClusterStackReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackClusterStackRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseList.
func (in *OpenStackClusterStackReleaseList) DeepCopy() *OpenStackClusterStackReleaseList {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackClusterStackReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseSpec) DeepCopyInto(out *OpenStackClusterStackReleaseSpec) {
	*out = *in
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(v1alpha7.OpenStackIdentityReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseSpec.
func (in *OpenStackClusterStackReleaseSpec) DeepCopy() *OpenStackClusterStackReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseStatus) DeepCopyInto(out *OpenStackClusterStackReleaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseStatus.
func (in *OpenStackClusterStackReleaseStatus) DeepCopy() *OpenStackClusterStackReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseTemplate) DeepCopyInto(out *OpenStackClusterStackReleaseTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseTemplate.
func (in *OpenStackClusterStackReleaseTemplate) DeepCopy() *OpenStackClusterStackReleaseTemplate {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackClusterStackReleaseTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseTemplateList) DeepCopyInto(out *OpenStackClusterStackReleaseTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackClusterStackReleaseTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseTemplateList.
func (in *OpenStackClusterStackReleaseTemplateList) DeepCopy() *OpenStackClusterStackReleaseTemplateList {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackClusterStackReleaseTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseTemplateResource) DeepCopyInto(out *OpenStackClusterStackReleaseTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseTemplateResource.
func (in *OpenStackClusterStackReleaseTemplateResource) DeepCopy() *OpenStackClusterStackReleaseTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseTemplateSpec) DeepCopyInto(out *OpenStackClusterStackReleaseTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseTemplateSpec.
func (in *OpenStackClusterStackReleaseTemplateSpec) DeepCopy() *OpenStackClusterStackReleaseTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackClusterStackReleaseTemplateStatus) DeepCopyInto(out *OpenStackClusterStackReleaseTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackClusterStackReleaseTemplateStatus.
func (in *OpenStackClusterStackReleaseTemplateStatus) DeepCopy() *OpenStackClusterStackReleaseTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackClusterStackReleaseTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackNodeImage) DeepCopyInto(out *OpenStackNodeImage) {
	*out = *in
	if in.CreateOpts != nil {
		in, out := &in.CreateOpts, &out.CreateOpts
		*out = new(images.CreateOpts)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackNodeImage.
func (in *OpenStackNodeImage) DeepCopy() *OpenStackNodeImage {
	if in == nil {
		return nil
	}
	out := new(OpenStackNodeImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackNodeImageRelease) DeepCopyInto(out *OpenStackNodeImageRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackNodeImageRelease.
func (in *OpenStackNodeImageRelease) DeepCopy() *OpenStackNodeImageRelease {
	if in == nil {
		return nil
	}
	out := new(OpenStackNodeImageRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackNodeImageRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackNodeImageReleaseList) DeepCopyInto(out *OpenStackNodeImageReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackNodeImageRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackNodeImageReleaseList.
func (in *OpenStackNodeImageReleaseList) DeepCopy() *OpenStackNodeImageReleaseList {
	if in == nil {
		return nil
	}
	out := new(OpenStackNodeImageReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackNodeImageReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackNodeImageReleaseSpec) DeepCopyInto(out *OpenStackNodeImageReleaseSpec) {
	*out = *in
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(v1alpha7.OpenStackIdentityReference)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(OpenStackNodeImage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackNodeImageReleaseSpec.
func (in *OpenStackNodeImageReleaseSpec) DeepCopy() *OpenStackNodeImageReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackNodeImageReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackNodeImageReleaseStatus) DeepCopyInto(out *OpenStackNodeImageReleaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackNodeImageReleaseStatus.
func (in *OpenStackNodeImageReleaseStatus) DeepCopy() *OpenStackNodeImageReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackNodeImageReleaseStatus)
	in.DeepCopyInto(out)
	return out
}
