apiVersion: infrastructure.clusterstack.x-k8s.io/v1alpha1
kind: OpenStackClusterStackReleaseTemplate
metadata:
  name: cspotemplate
  namespace: cluster
spec:
  template:
    spec:
      cloudName: <name of the cloud to use from the clouds secret>
      identityRef:
        kind: Secret
        name: <my-secret>
