name: cspo Image Cache Cleaner
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Run the GC on the first day in the month at 6am
    - cron: "0 6 1 * *"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true
jobs:
  cache-cleaner:
    runs-on: ubuntu-24.04
    steps:
      # Load Golang cache build from GitHub
      - name: Load cspo Golang cache build from GitHub
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: cache
        with:
          path: /tmp/.cache/cspo
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-cspo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-cspo-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-
      - name: Create cspo cache directory
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/cspo
      # Clean docker's golang's cache
      - name: Clean cspo Golang cache from GitHub
        shell: bash
        run: |
          rm -f /tmp/.cache/cspo/go-build-cache.tar.gz
          rm -f /tmp/.cache/cspo/go-pkg-cache.tar.gz
