name: Test Code
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - "releases/**"
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
      - ".github/workflows/**"
      - "Makefile"
      - "images/builder/**"
      - "images/**"
      - "test/releases/**"
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true
jobs:
  test:
    name: Test Code
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Coverage result name
        id: name
        run: |
          if [ ${{ github.event.pull_request }} ]; then
          NAME=pr-${{ github.event.pull_request.number }}
          else
          NAME=${{ github.sha }}
          fi
          echo name=${NAME} >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Install dependencies
        run: make gotestsum go-cover-treemap setup-envtest helm

      - name: Install go modules for test
        shell: bash
        run: |
          go mod download

      - name: Running unit tests
        run: make test-unit

      - name: Running integration tests
        env:
          GIT_PROVIDER: github
          # TODO: Change GIT_ORG_NAME to SovereignCloudStack
          # when repo SovereignCloudStack/cluster-stack will
          # have correct and stable releases for OpenStack
          GIT_ORG_NAME: chess-knight
          GIT_REPOSITORY_NAME: cluster-stacks
          GO111MODULE: "on"
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          ENCODED_CLOUDS_YAML: ${{ secrets.ENCODED_CLOUDS_YAML }}
        run: make test-integration

      # - name: Create Report
      #   run: make report-cover-html report-cover-treemap
      # - name: Running integration tests
      #   env:
      #     GIT_PROVIDER: github
      #     GIT_ORG_NAME: sovereignCloudStack
      #     GIT_REPOSITORY_NAME: fake-cluster-stacks
      #     GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      #   run: make test-integration

      # - name: Test Summary
      #   uses: test-summary/action@62bc5c68de2a6a0d02039763b8c754569df99e3f # v2.1
      #   with:
      #     paths: ".coverage/junit.xml"

      # - name: Upload Report
      #   uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      #   with:
      #     name: reports-${{ steps.name.outputs.name }}
      #     path: .reports
      #     retention-days: 30
